### ISSUE TITLE
Adapting this for ESP32 and the newest release of MicroPython

### ISSUE THREAD

**Issue by mukulpareek** [pdwerryhouse/max7219_8digit#2]
Hi, this is a great library, but it does not seem to work on ESP32 with the latest MicroPython releases.  Several functions don't seem to exist/have been deprecated.  Possibly hardware differences too between the 8266 and ESP32.  How can this be adapted to the ESP32?

**Comment by pdwerryhouse** [comment]
Thanks for reporting this. The issue was just on the newer releases of Micropython - I have updated it to work with version 1.19.1 and have tested that it works with both the ESP8266 and ESP32.
